version: '3'
services:
  kaisen:
    image: bihan001/kaisen:dev
    build:
      context: ./
      target: dev
    container_name: kaisen-os-dev
    restart: always
    volumes:
      - ./:/app
    ports:
      - '5000:5000'
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - BACKEND_PORT=5000
      - PORT=3000 # Frontend port
      - MONGODB_URI=mongodb+srv://kaisen:kaisen@kaisen-test-cluster.hllyu.mongodb.net/test-db?retryWrites=true&w=majority
      - FIREBASE_URI=https://mern-authentication-6634c.firebaseio.com
      - SERVICE_ACCOUNT_PATH=/app/serviceAccount.json
